################################
## Houston Bootstrap Secrets
#################################
kind: Secret
apiVersion: v1
metadata:
  name: astronomer-root-admin-credentials
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    component: astronomer-root-admin-credentials
type: Opaque
data:
  username: {{ "root@example.com" | b64enc | quote }}
  password: {{ randAlphaNum 20 | b64enc | quote }}
