################################
## Fluentd DaemonSet
#################################
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: {{ template "fluentd.fullname" . }}
  labels:
    tier: logging
    component: {{ template "fluentd.name" . }}
    chart: {{ template "fluentd.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      tier: logging
      component: {{ template "fluentd.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        tier: logging
        component: {{ template "fluentd.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/fluentd-configmap.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.ports.promScrape | quote }}
    spec:
      nodeSelector:
{{ toYaml (.Values.nodeSelector) | indent 8 }}
      affinity:
{{ toYaml (.Values.affinity) | indent 8 }}
      tolerations:
{{ toYaml (.Values.tolerations) | indent 8 }}
      serviceAccountName: {{ template "fluentd.fullname" . }}
      containers:
      - name: fluentd
        image: {{ template "fluentd.image" . }}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - if (( $(ruby -e "require 'net/http';require 'uri';uri = URI.parse('http://127.0.0.1:{{ .Values.ports.promScrape }}/metrics');response
              = Net::HTTP.get_response(uri);puts response.body" | grep 'fluentd_output_status_buffer_queue_length{'
              | awk '{ print ($NF > {{ .Values.livenessProbeConfig.bufferSizeUnhealthy }}) }') )); then exit 1; fi; exit 0
          failureThreshold: {{ .Values.livenessProbeConfig.failureThreshold }}
          initialDelaySeconds: {{ .Values.livenessProbeConfig.initialDelaySeconds5 }}
          periodSeconds: {{ .Values.livenessProbeConfig.periodSeconds5 }}
          successThreshold: {{ .Values.livenessProbeConfig.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbeConfig.timeoutSeconds }}
        imagePullPolicy: {{ .Values.images.fluentd.pullPolicy }}
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        - name: OUTPUT_HOST
          value: {{ template "elasticsearch.host" . }}
        - name: OUTPUT_PORT
          value: {{ .Values.elasticsearch.port | quote }}
        - name: OUTPUT_BUFFER_CHUNK_LIMIT
          value: {{ .Values.elasticsearch.buffer_chunk_limit | quote }}
        - name: OUTPUT_BUFFER_QUEUE_LIMIT
          value: {{ .Values.elasticsearch.buffer_queue_limit | quote }}
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: RELEASE
          value: {{ .Release.Name | quote }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: libsystemddir
          mountPath: /host/lib
          readOnly: true
        - name: config-volume-{{ template "fluentd.fullname" . }}
          mountPath: /etc/fluent/config.d
        resources:
{{ toYaml .Values.resources | indent 12 }}
        ports:
          - name: monitor-agent
            containerPort: {{ .Values.ports.promScrape }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: libsystemddir
        hostPath:
          path: /usr/lib64
      - name: config-volume-{{ template "fluentd.fullname" . }}
        configMap:
          name: {{ template "fluentd.fullname" . }}
