################################
## Fluentd PSP RoleBinding
################################
{{- if .Values.global.pspEnabled }}
apiVersion: {{ template "apiVersion.rbac" . }}
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-psp-fluentd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-psp-fluentd
subjects:
- kind: ServiceAccount
  name: {{ template "fluentd.fullname" . }}
{{- end -}}
