{{- if .Values.global.pspEnabled }}
################################
## Fluentd PSP RoleBinding
#################################
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-psp-fluentd
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-psp-fluentd
subjects:
- kind: ServiceAccount
  name: {{ template "fluentd.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
