################################
## Fluentd DaemonSet
#################################
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    tier: logging
    component: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      tier: logging
      component: {{ template "name" . }}
      release: {{ .Release.Name }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  template:
    metadata:
      labels:
        tier: logging
        component: {{ template "name" . }}
        release: {{ .Release.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/fluentd-configmap.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.ports.promScrape | quote }}
    spec:
      serviceAccountName: {{ template "fullname" . }}
      containers:
      - name: {{ template "fullname" . }}
        image: {{ template "fluentd_image" . }}
        imagePullPolicy: {{ .Values.images.fluentd.pullPolicy }}
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        - name: OUTPUT_HOST
          value: {{ template "elasticsearch_host" . }}
        - name: OUTPUT_PORT
          value: {{ .Values.elasticsearch.port | quote }}
        - name: OUTPUT_BUFFER_CHUNK_LIMIT
          value: {{ .Values.elasticsearch.buffer_chunk_limit | quote }}
        - name: OUTPUT_BUFFER_QUEUE_LIMIT
          value: {{ .Values.elasticsearch.buffer_queue_limit | quote }}
        - name: K8S_NAMESPACE
          value: "{{ .Release.Namespace }}"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: libsystemddir
          mountPath: /host/lib
          readOnly: true
        - name: config-volume-{{ template "fullname" . }}
          mountPath: /etc/fluent/config.d
        resources:
{{ toYaml .Values.resources | indent 12 }}
        ports:
          - name: monitor-agent
            containerPort: {{ .Values.ports.promScrape }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: libsystemddir
        hostPath:
          path: /usr/lib64
      - name: config-volume-{{ template "fullname" . }}
        configMap:
          name: {{ template "fullname" . }}
