# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nodeSelector: {}
affinity: {}
tolerations: []

images:
  nginx:
    repository: quay.io/astronomer/ap-nginx
    tag: 0.47.0
    pullPolicy: IfNotPresent
  defaultBackend:
    repository: quay.io/astronomer/ap-default-backend
    tag: 0.25.2
    pullPolicy: IfNotPresent

ingressClass: ~

replicas: 2
replicasDefaultBackend: 2
# These are only applicable when respective replicas > 3
maxUnavailable: 25%
maxUnavailableDefaultBackend: 25%

resources: {}
#  limits:
#   cpu: 100m
#   memory: 128Mi
#  requests:
#   cpu: 100m
#   memory: 128Mi

# Service type that Nginx can be. Default is LoadBalancer but "ClusterIP" and "NodePort" are both valid.
serviceType: "LoadBalancer"

# dict of annotations to add to the ingress controller
ingressAnnotations: {}

# AntiAffinity can be "hard" or "soft"
antiAffinity: "soft"

# String IP address the nginx ingress should bind to
loadBalancerIPs: ~

# String IP address that the service should list as an external IP. Currently only 1 address is supported
externalIPs: ~

# List used to restrict IPs that can reach the nginx ingress
loadBalancerSourceRanges: []

# Set to 'true' when deploying to a private EKS cluster
privateLoadBalancer: false

# Dependent on cloud provider
preserveSourceIP: false

proxyConnectTimeout: 15
proxyReadTimeout: 600
proxySendTimeout: 600
proxyBodySize: "1024m"
hstsIncludeSubdomains: false
serverNameHashBucketSize: 256

ports:
  http: 8080
  https: 8443
  defaultBackendHTTP: 8080
  healthz: 10254
  metrics: 10254
