################################
## Astronomer Prisma Deployment
#################################
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ .Release.Name }}-prisma
  labels:
    component: prisma
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: astronomer
      component: prisma
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        component: prisma
        tier: astronomer
        release: {{ .Release.Name }}
    spec:
      nodeSelector:
{{ toYaml (default .Values.global.platformNodePool.nodeSelector .Values.nodeSelector) | indent 8 }}
      affinity:
{{ toYaml (default .Values.global.platformNodePool.affinity .Values.affinity) | indent 8 }}
      tolerations:
{{ toYaml (default .Values.global.platformNodePool.tolerations .Values.tolerations) | indent 8 }}
      restartPolicy: Always
      {{- if and (not .Values.houston.backendSecretName) (not .Values.houston.backendConnection) }}
      serviceAccountName: {{ template "prisma.bootstrapperServiceAccount" . }}
      initContainers:
        - name: bootstrapper
          image: {{ template "dbBootstrapper.image" . }}
          imagePullPolicy: {{ .Values.images.dbBootstrapper.pullPolicy }}
          env:
            - name: BOOTSTRAP_DB
              valueFrom:
                secretKeyRef:
                  name: astronomer-bootstrap
                  key: connection
            - name: DB_NAME
              value: {{ .Release.Name }}-houston
            - name: SECRET_NAME
              value: {{ template "houston.backendSecret" . }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: IN_CLUSTER
              value: "true"
      {{- end }}
      containers:
        - name: prisma
          image: {{ template "prisma.image" . }}
          imagePullPolicy: {{ .Values.images.prisma.pullPolicy }}
          resources:
{{ toYaml .Values.prisma.resources | indent 12 }}
          ports:
            - name: prisma-http
              containerPort: {{ .Values.ports.prismaHTTP }}
          # Use prisma unofficial health check https://www.prisma.io/forum/t/health-check-url/5344
          readinessProbe:
            httpGet:
              path: /management
              port: {{ .Values.ports.prismaHTTP }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          env:
            {{- range $i, $config := .Values.prisma.env }}
            - name: {{ $config.name }}
              value: {{ $config.value | quote }}
            {{- end }}
            - name: CONFIG
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-prisma-config
                  key: config.yml
            - name: PRISMA_CONFIG_PATH
              value: /app/config.yml
            - name: PRISMA_DB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ template "houston.backendSecret" . }}
                  key: connection
            - name: PRISMA_MANAGEMENT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-prisma-api-secret
                  key: api-secret
