#######################################
## Create Root Admin Job
#######################################
apiVersion: {{ include "apiVersion.batch.cronjob" . }}
kind: CronJob
metadata:
  name: {{ .Release.Name }}-upd-root-adm-pwd-cron
  labels:
    tier: astronomer
    component: houston-update-root-admin-password-cronjob
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "0 5 31 2 *" # https://crontab.guru/#0_5_31_2_*  At 05:00 on day-of-month 31 in February.
  # this cronjob is only intended for manually triggering
  suspend: true
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            tier: astronomer
            component: houston-update-root-admin-password-cronjob
            release: {{ .Release.Name }}
            app: houston-update-root-admin-password-cronjob
            version: {{ .Chart.Version }}
          {{- if .Values.global.istio.enabled }}
          annotations:
            sidecar.istio.io/inject: "false"
          {{- end }}
        spec:
          nodeSelector:
{{ toYaml (default .Values.global.platformNodePool.nodeSelector .Values.nodeSelector) | indent 12 }}
          affinity:
{{ toYaml (default .Values.global.platformNodePool.affinity .Values.affinity) | indent 12 }}
          tolerations:
{{ toYaml (default .Values.global.platformNodePool.tolerations .Values.tolerations) | indent 12 }}
          restartPolicy: Never
{{- include "astronomer.imagePullSecrets" . | indent 10 }}
          containers:
            - name: update-root-admin-password-job
              image: {{ template "houston.image" . }}
              imagePullPolicy: {{ .Values.images.houston.pullPolicy }}
              volumeMounts:
                {{- include "houston_volume_mounts" . | indent 16 }}
                {{- include "custom_ca_volume_mounts" . | indent 16 }}
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "houston.backendSecret" . }}
                      key: connection
                - name: ROOT_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: astronomer-root-admin-credentials
                      key: password
              command: ["yarn"]
              # If you supply only args for a Container, the default Entrypoint defined in the Docker image is run with the args that you supplied.
              args: ["update-root-admin-password", "--password=$(ROOT_ADMIN_PASSWORD)"]
          volumes:
            {{- include "houston_volumes" . | indent 12 }}
            {{- include "custom_ca_volumes" . | indent 12 }}
