########################################
## Elasticsearch Logging Ingress ##
########################################
{{- if or (eq .Values.global.plane.mode "data") (eq .Values.global.plane.mode "unified") }}
kind: Ingress
apiVersion: {{ template "apiVersion.Ingress" . }}
metadata:
  name: {{ template "elasticsearch.fullname" . }}-ingress
  labels:
    tier: logging
    component: {{ template "elasticsearch.name" . }}-logging-ingress
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    plane: {{ .Values.global.plane.mode }}
    {{- include "global.podLabels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.authSidecar.enabled  }}
      {{- toYaml .Values.global.extraAnnotations | nindent 4 }}
    {{- else }}
    {{- if .Values.global.extraAnnotations }}
      {{- toYaml .Values.global.extraAnnotations | nindent 4 }}
    {{- end }}
    kubernetes.io/ingress.class: "{{ .Release.Name }}-nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- end }}
    {{- if .Values.ingress.annotation  }}
    {{- toYaml .Values.ingress.annotation  | nindent 4  }}
    {{- end }}
spec:
  {{- if .Values.global.tlsSecret }}
  tls:
    - secretName: {{ .Values.global.tlsSecret }}
  {{- end }}
      hosts:
        - {{ template "elasticsearch.ingressurl" . }}
  rules:
    - host: {{ template "elasticsearch.ingressurl" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-elasticsearch
                port:
                  number: {{ .Values.common.ports.http }}
{{- end }}
