################################
## Airflow StatsD Deployment
#################################
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ .Release.Name }}-statsd
  labels:
    tier: airflow
    component: statsd
    release: {{ .Release.Name }}
    platform: {{ .Values.platform.release }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: airflow
      component: statsd
      release: {{ .Release.Name }}
      platform: {{ .Values.platform.release }}
      workspace: {{ .Values.platform.workspace | quote }}
  template:
    metadata:
      labels:
        tier: airflow
        component: statsd
        release: {{ .Release.Name }}
        platform: {{ .Values.platform.release }}
        workspace: {{ .Values.platform.workspace | quote }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-statsd
          image: {{- include "statsd_image" . | indent 1 }}
          imagePullPolicy: {{ .Values.images.statsd.pullPolicy }}
          args:
            - "-statsd.mapping-config=/etc/statsd-exporter/mappings.yml"
          resources:
{{ toYaml .Values.statsd.resources | indent 12 }}
          ports:
            - name: statsd-ingest
              protocol: UDP
              containerPort: {{ .Values.ports.statsdIngest }}
            - name: statsd-scrape
              containerPort: {{ .Values.ports.statsdScrape }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.ports.statsdScrape }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.ports.statsdScrape }}
            initialDelaySeconds: 10
            periodSeconds: 10
