################################
## Airflow StatsD Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-statsd
  labels:
    tier: airflow
    component: statsd
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
    {{- if .Values.platform.release }}
    astronomer.io/platform-release: {{ .Values.platform.release }}
    {{- end }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.ports.statsdScrape | quote }}
spec:
  type: ClusterIP
  selector:
    tier: airflow
    component: statsd
    release: {{ .Release.Name }}
  ports:
    - name: statsd-ingest
      protocol: UDP
      port: {{ .Values.ports.statsdIngest }}
      targetPort: {{ .Values.ports.statsdIngest }}
    - name: statsd-scrape
      protocol: TCP
      port: {{ .Values.ports.statsdScrape }}
      targetPort: {{ .Values.ports.statsdScrape }}
