################################
## Airflow Webserver Deployment
#################################
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-webserver
  labels:
    tier: airflow
    component: webserver
    release: {{ .Release.Name }}
    platform: {{ .Values.platform.release }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.webserver.replicas }}
  selector:
    matchLabels:
      tier: airflow
      component: webserver
      release: {{ .Release.Name }}
      platform: {{ .Values.platform.release }}
      workspace: {{ .Values.platform.workspace | quote }}
  template:
    metadata:
      labels:
        tier: airflow
        component: webserver
        release: {{ .Release.Name }}
        platform: {{ .Values.platform.release }}
        workspace: {{ .Values.platform.workspace | quote }}
      annotations:
        checksum/metadata-secret: {{ include (print $.Template.BasePath "/secrets/metadata-connection-secret.yaml") . | sha256sum }}
        checksum/pgbouncer-config-secret: {{ include (print $.Template.BasePath "/secrets/pgbouncer-config-secret.yaml") . | sha256sum }}
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: {{ .Values.uid }}
      {{- if or .Values.registry.secretName .Values.registry.connection }}
      imagePullSecrets:
        - name: {{ template "registry_secret" . }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-webserver
          image: {{ template "airflow_image" . }}
          imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
          args: ["airflow", "webserver"]
          resources:
{{ toYaml .Values.webserver.resources | indent 12 }}
          ports:
            - name: webserver-ui
              containerPort: {{ .Values.ports.airflowUI }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.airflowUI }}
            initialDelaySeconds: {{ .Values.webserver.initialDelaySeconds | default 10 }}
            timeoutSeconds: {{ .Values.webserver.timeoutSeconds | default 30 }}
            failureThreshold: {{ .Values.webserver.failureThreshold | default 10 }}
            periodSeconds: {{ .Values.webserver.periodSeconds | default 5 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.airflowUI }}
            initialDelaySeconds: {{ .Values.webserver.initialDelaySeconds | default 10 }}
            timeoutSeconds: {{ .Values.webserver.timeoutSeconds | default 30 }}
            failureThreshold: {{ .Values.webserver.failureThreshold | default 10 }}
            periodSeconds: {{ .Values.webserver.periodSeconds | default 5 }}
          env:
          {{- include "custom_airflow_environment" . | indent 10 }}
          {{- include "standard_airflow_environment" . | indent 10 }}
