##################################
#                                #
#  NATS Streaming Configuration  #
#                                #
##################################
images:
  init:
    repository: quay.io/astronomer/ap-base
    tag: 3.14.0
    pullPolicy: IfNotPresent
  stan:
    repository: quay.io/astronomer/ap-nats-streaming
    tag: 0.22.0
    pullPolicy: IfNotPresent

stan:
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi

  # Cluster name, generated into a name from the
  # release name by default.
  clusterID:

  logging:
    debug: true
    trace:

  # In case of NATS not being embedded then
  # an URL for NATS is required.
  nats:
    port: 4222
    serviceRoleAuth:
      enabled: false
      natsClusterName:

  # TLS
  # Enabled must be true, and a secret name specified for this to work
  tls:
    enabled: false
    # the secret containing the client ca.crt, tls.crt, and tls.key for STAN
    secretName:
    # Reference
    # https://docs.nats.io/nats-streaming-server/configuring/cfgfile#tls-configuration
    settings:
      client_cert: "/etc/nats/certs/tls.crt"
      client_key: "/etc/nats/certs/tls.key"
      client_ca: "/etc/nats/certs/ca.crt"
      timeout: 3

nameOverride: ""
imagePullSecrets: {}

# Toggle whether to use setup a Pod Security Context
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsUser: 1000

# Affinity for pod assignment
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

###########################
#                         #
#  Storage configuration  #
#                         #
###########################
store:
  # One value possible out of: "file" | "sql" | "memory"
  type: file

  #
  # Fault tolerance group
  #
  ft:
    group:

  # Configures streaming/store_limits as is.
  #
  # NOTE: Section in snake case since they will become
  # the same objects.
  #
  # Look at the NATS Streaming configuration for this:
  #
  # https://docs.nats.io/nats-streaming-server/configuring/cfgfile#store-limits-configuration
  #
  limits: {}

  #
  # Volume claim configuration. Required if the store type is `file` or if
  # cluster is enabled.
  #
  volume:
    enabled: true
    mount: /data/stan
    storageSize: 1Gi
    accessModes: ReadWriteOnce
    storageClass:

  #
  # File storage settings.
  #
  file:
    path: /data/stan/store

  # In case of using file or sql storage, sets up a 3 node cluster.
  cluster:
    enabled: true
    logPath: /data/stan/log

  #
  # SQL storage settings
  #
  sql:
    driver: postgres

    # TODO: Use secret reference and include instead for the password.
    #
    # e.g.
    # source: "dbname=postgres user=postgres password=stan host=stan-db sslmode=disable"
    #
    source: ""

    # Initialize the database.
    initdb:
      enabled: false

      # Client to use to init the db.
      image: postgres:11

    dbName: postgres
    dbUser: postgres
    dbPassword: stan
    dbHost: ""
    dbPort: 5432

#######################################
#                                     #
# Prometheus Exporter configuration   #
#                                     #
#######################################
exporter:
  enabled: true
  image: quay.io/astronomer/ap-nats-exporter:0.6.2-1
  pullPolicy: IfNotPresent
  resources: {}
  #  limits:
  #   cpu: 100m
  #   memory: 128Mi
  #  requests:
  #   cpu: 100m
  #   memory: 128Mi
##################################
#                                #
#  Embedded NATS Configuration   #
#                                #
##################################
# TODO: Support NATS embedded mode by including
# nats chart values.
