################################
## NGINX Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    tier: {{ template "nginx.name" . }}
    component: ingress-controller
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # AWS annotations
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

    {{- if .Values.privateLoadBalancer }}
    # This annotation is detected by EKS to indicate that
    # it should provision a private ("internal") load balancer
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    cloud.google.com/load-balancer-type: "Internal"
    {{- end }}

    # Metrics annotations
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.ports.metrics | quote }}
spec:
  type: LoadBalancer
  {{- if .Values.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  {{- end }}
  {{- if .Values.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ .Values.loadBalancerSourceRanges }}
  {{- end }}
  {{- if .Values.preserveSourceIP }}
  externalTrafficPolicy: "Cluster"
  {{- end }}
  selector:
    tier: {{ template "nginx.name" . }}
    component: ingress-controller
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.ports.http }}
      targetPort: {{ .Values.ports.http }}
      protocol: TCP
      name: http
    - port: {{ .Values.ports.https }}
      targetPort: {{ .Values.ports.https }}
      protocol: TCP
      name: https
    - port: {{ .Values.ports.metrics }}
      targetPort: {{ .Values.ports.metrics }}
      protocol: TCP
      name: metrics
