################################
## NGINX Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    tier: {{ template "nginx.name" . }}
    component: ingress-controller
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if .Values.ingressAnnotations -}}
{{ range $key, $value := .Values.ingressAnnotations }}
    {{ $key }}: {{ $value }}
{{- end -}}
{{- end -}}
    {{- if .Values.privateLoadBalancer }}
    # This annotation is detected by EKS to indicate that
    # it should provision a private ("internal") load balancer
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    cloud.google.com/load-balancer-type: "Internal"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: "private"
    {{- end }}

    # Metrics annotations
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.ports.metrics | quote }}
spec:
  type: {{ .Values.serviceType }}
  {{- if .Values.externalIPs }}
  externalIps:
    - {{ .Values.externalIPs }}
  {{- end }}
  {{- if .Values.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  {{- end }}
  {{- if .Values.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ .Values.loadBalancerSourceRanges | toJson }}
  {{- end }}
  {{- if .Values.preserveSourceIP }}
  externalTrafficPolicy: "Cluster"
  {{- end }}
  selector:
    tier: {{ template "nginx.name" . }}
    component: ingress-controller
    release: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.ports.http }}
      protocol: TCP
      name: http
    - port: 443
      targetPort: {{ .Values.ports.https }}
      protocol: TCP
      name: https
    - port: {{ .Values.ports.metrics }}
      targetPort: {{ .Values.ports.metrics }}
      protocol: TCP
      name: metrics
