################################
## Prometheus Cluster Role Binding
#################################
{{- if .Values.global.rbacEnabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-prometheus"
  labels:
    tier: monitoring
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Release.Name }}-prometheus"
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}-prometheus"
    namespace: {{ .Release.Namespace }}
{{- end }}
