################################
## Airflow Flower Deployment
#################################
{{- if eq .Values.executor "CeleryExecutor" }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-flower
  labels:
    tier: airflow
    component: flower
    release: {{ .Release.Name }}
    platform: {{ .Values.platform.release }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: airflow
      component: flower
      release: {{ .Release.Name }}
      platform: {{ .Values.platform.release }}
      workspace: {{ .Values.platform.workspace | quote }}
  template:
    metadata:
      labels:
        tier: airflow
        component: flower
        release: {{ .Release.Name }}
        platform: {{ .Values.platform.release }}
        workspace: {{ .Values.platform.workspace | quote }}
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: {{ .Values.uid }}
      {{- if or .Values.registry.secretName .Values.registry.connection }}
      imagePullSecrets:
        - name: {{ template "registry_secret" . }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-flower
          image: {{- include "flower_image" . | indent 1 }}
          imagePullPolicy: {{ .Values.images.flower.pullPolicy }}
          args: ["airflow", "flower"]
          resources:
{{ toYaml .Values.flower.resources | indent 12 }}
          ports:
            - name: flower-ui
              containerPort: {{ .Values.ports.flowerUI }}
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: {{ .Values.ports.flowerUI }}
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: {{ .Values.ports.flowerUI }}
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
          {{- include "airflow_environment" . | indent 10 }}
{{- end }}
