################################
## Airflow Flower NetworkPolicy
#################################
{{- if (and .Values.networkPolicies.enabled (eq .Values.executor "CeleryExecutor")) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-flower-policy
  labels:
    tier: airflow
    component: airflow-flower-policy
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: airflow
      component: flower
      release: {{ .Release.Name }}
      workspace: {{ .Values.platform.workspace | quote }}
  policyTypes:
  - Ingress
{{- if .Values.platform.release }}
  ingress:
  - from:
    - namespaceSelector: {}
    - podSelector:
        matchLabels:
          tier: nginx
          component: ingress-controller
          release: {{ .Values.platform.release }}
    ports:
    - protocol: TCP
      port: {{ .Values.ports.flowerUI }}
{{- end }}
{{- end }}
