###################################
## Astronomer Cluster Local Data ##
###################################
{{- $configMapName := printf "%s-cluster-local-data" .Release.Name }}
{{- $configMapObj := (lookup "v1" "ConfigMap" .Release.Namespace $configMapName) | default dict }}
{{- $configLocalClusterID := (get $configMapObj "local_cluster_id") | default (randAlphaNum 12) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/resource-policy": keep
  labels:
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    plane: {{ .Values.global.plane.mode }}
data:
  local_cluster_id: {{ $configLocalClusterID }}
