# Namespace Pools - create user-defined namespaces to host Airflow deployments
{{- if and .Values.global.features.namespacePools.enabled .Values.global.features.namespacePools.namespaces.create }}
{{- $namespaceLabels := .Values.global.namespaceLabels }}
{{- range $i, $namespaceName := .Values.global.features.namespacePools.namespaces.names }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespaceName }}
  annotations:
    # Keep namespaces if user disable namespace pools later on
    "helm.sh/resource-policy": keep
  {{- if $namespaceLabels }}
  labels:
    {{- $namespaceLabels | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
