################################
## Astronomer Orbit Deployment
#################################
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: {{ .Release.Name }}-orbit
  labels:
    component: orbit
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orbit
      tier: astronomer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        component: orbit
        tier: astronomer
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-orbit
          image: {{- include "orbit_image" . | indent 1 }}
          imagePullPolicy: {{ .Values.images.orbit.pullPolicy }}
          resources:
{{ toYaml .Values.orbit.resources | indent 12 }}
          ports:
            - name: orbit-http
              containerPort: {{ .Values.ports.orbitHTTP }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.ports.orbitHTTP }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.ports.orbitHTTP }}
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            {{- range $i, $config := .Values.orbit.env }}
            - name: {{ $config.name }}
              value: {{ $config.value | quote }}
            {{- end }}
            {{- if .Values.global.baseDomain }}
            - name: APP_API_LOC_HTTPS
              value: "https://houston.{{ .Values.global.baseDomain }}/v1"
            {{- end }}
            - name: ANALYTICS_TRACKING_ID
              value: "pFWwGe5wXTK5e26mWAarQ"
