################################
## Astronomer Orbit Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-orbit
  labels:
    component: orbit
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    component: orbit
    tier: astronomer
    release: {{ .Release.Name }}
  ports:
    - name: orbit-http
      protocol: TCP
      port: 8080
      targetPort: 8080
