################################
## Alertmanager sidecar ConfigMap
#################################
{{- if .Values.global.authSidecar.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "alertmanager.fullname" . }}-nginx-conf
  labels:
    tier: monitoring
    component: {{ template "alertmanager.name" . }}
    chart: {{ template "alertmanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  default.conf: |
    upstream astro-alertmanager {
      server {{ .Release.Name }}-alertmanager:{{ .Values.ports.http }} ;
    }
    server {
      server_name {{ template "alertmanager.url" . }} ;
      listen 8080  ;
      listen [::]:8080  ;
      location  = /auth {
        proxy_set_header Host houston.{{ .Values.global.baseDomain }};
        proxy_pass  https://houston.{{ .Values.global.baseDomain }}/v1/authorization;
        {{ .Values.global.default_nginx_settings }}
      }
      location @401_auth_error {
        internal;
        add_header Set-Cookie $auth_cookie;
        return 302 https://app.{{ .Values.global.baseDomain }}/login?rd=https://$http_host$request_uri;
      }
      location / {
        # Custom headers to proxied server
        proxy_set_header  Host  {{ template "alertmanager.url" . }};
        proxy_pass http://astro-alertmanager;
        {{ .Values.global.default_nginx_settings_location }}
      }
    }
{{- end }}
