################################
## Airflow Scheduler PodDisruptionBudget
#################################
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata:
  name: {{ .Release.Name }}-pdb
  labels:
    tier: airflow
    component: scheduler
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      tier: airflow
      component: scheduler
      release: {{ .Release.Name }}
      workspace: {{ .Values.workspace }}
{{ toYaml .Values.scheduler.podDisruptionBudget | indent 2 }}
