#################################
## Postgres Operator Deployment #
#################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "postgres-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "9"
  labels:
    tier: {{ template "postgres-operator.name" . }}
    component: {{ template "postgres-operator.name" . }}
    chart: {{ template "postgres-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.operator.replicas }}
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      tier: {{ template "postgres-operator.name" . }}
      component: {{ template "postgres-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        tier: {{ template "postgres-operator.name" . }}
        component: {{ template "postgres-operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "postgres-operator.serviceAccountName" . }}
      containers:
      - name: postgres-operator
        # IMPORTANT when we inevitably need to upgrade this we need to make sure we also copy the new crd file ./crds/postgresql.crd.yaml
        image: {{ include "operator.image" . }}
        imagePullPolicy: {{ .Values.images.operator.pullPolicy }}
        resources:
{{ toYaml .Values.operator.resources | indent 10 }}
        securityContext:
{{ toYaml .Values.operator.securityContext | indent 10 }}
        env:
        - name: CONFIG_MAP_NAME
          value: "{{ template "postgres-operator.fullname" . }}-configmap"
{{- if .Values.operator.extraEnvs }}
{{ toYaml .Values.operator.extraEnvs | indent 8 }}
{{- end }}
