################################
## KubeD Deployment
#################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kubed.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: {{ template "kubed.name" . }}
    component: {{ template "kubed.name" . }}
    chart: {{ template "kubed.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      tier: {{ template "kubed.name" . }}
      component: {{ template "kubed.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        tier: {{ template "kubed.name" . }}
        component: {{ template "kubed.name" . }}
        release: {{ .Release.Name }}
{{- if or .Values.annotations (and .Values.criticalAddon (eq .Release.Namespace "kube-system")) }}
      annotations:
{{- if and .Values.criticalAddon (eq .Release.Namespace "kube-system") }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
{{- end }}
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
{{- end }}
    spec:
      nodeSelector:
{{ toYaml (default .Values.global.platformNodePool.nodeSelector .Values.nodeSelector) | indent 8 }}
      affinity:
{{ toYaml (default .Values.global.platformNodePool.affinity .Values.affinity) | indent 8 }}
      tolerations:
{{ toYaml (default .Values.global.platformNodePool.tolerations .Values.tolerations) | indent 8 }}
      serviceAccountName: {{ template "kubed.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
      {{- end }}
      containers:
      - name: {{ template "kubed.fullname" . }}
        image: {{ include "kubed.image" . }}
        imagePullPolicy: {{ .Values.images.kubed.pullPolicy }}
        args:
        - run
        - --v={{ .Values.logLevel }}
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --use-kubeapiserver-fqdn-for-aks={{ .Values.apiserver.useKubeapiserverFqdnForAks }}
        - --enable-analytics={{ .Values.enableAnalytics }}
        - --config-source-namespace={{ .Release.Namespace }}
        ports:
        - containerPort: 8443
{{- if .Values.apiserver.healthcheck.enabled }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          timeoutSeconds: 5
          initialDelaySeconds: 5
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: config
          mountPath: /srv/kubed
        - name: scratch
          mountPath: /tmp
        - mountPath: /var/serving-cert
          name: serving-cert
      {{- if .Values.persistence.enabled }}
        - name: storage
          mountPath: "/var/lib/kubed"
        {{- if .Values.persistence.subPath }}
            subPath: {{ .Values.persistence.subPath }}
        {{- end }}
      {{- end }}
      volumes:
      - name: config
        secret:
          secretName: {{ template "kubed.fullname" . }}
      - name: scratch
        emptyDir: {}
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ template "kubed.fullname" . }}-apiserver-cert
      {{- if .Values.persistence.enabled }}
      - name: storage
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "kubed.fullname" . }}{{- end }}
      {{- end }}
