################################
## Pgbouncer NetworkPolicy
#################################
{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-pgbouncer-policy
  labels:
    tier: airflow
    component: airflow-pgbouncer-policy
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  podSelector:
    matchLabels:
      tier: airflow
      component: pgbouncer
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: airflow
          release: {{ .Release.Name }}
    {{- if .Values.platform.release }}
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          tier: monitoring
          component: prometheus
          release: {{ .Values.platform.release }}
    {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.ports.pgbouncer }}
  {{- if .Values.platform.release }}
    - protocol: TCP
      port: {{ .Values.ports.pgbouncerScrape }}
  {{- end }}
{{- end }}
