################################
## Pgbouncer NetworkPolicy
#################################
{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-pgbouncer-policy
  labels:
    tier: airflow
    component: airflow-pgbouncer-policy
    release: {{ .Release.Name }}
    workspace: {{ .Values.platform.workspace | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: airflow
      component: pgbouncer
      release: {{ .Release.Name }}
      workspace: {{ .Values.platform.workspace | quote }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
    - podSelector:
        matchLabels:
          tier: airflow
          release: {{ .Release.Name }}
          workspace: {{ .Values.platform.workspace | quote }}
    {{- if .Values.platform.release }}
    - podSelector:
        matchLabels:
          tier: monitoring
          component: prometheus
          release: {{ .Values.platform.release }}
    {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.ports.pgbouncer }}
  {{- if .Values.platform.release }}
    - protocol: TCP
      port: {{ .Values.ports.pgbouncerScrape }}
  {{- end }}
{{- end }}
