enabled: true

keda:
  image:
    # Enable KEDA POC in cloud
    keda: "astronomerinc/ap-keda:0.11.1"
    metricsAdapter: "astronomerinc/ap-keda-metrics-adapter:0.11.1"
  nodeSelector: {{ .Values.global.platformNodePool.nodeSelector }}
  tolerations: {{ .Values.global.platformNodePool.tolerations }}
  affinity: {{ .Values.global.platformNodePool.affinity }}