################################
## Redis NetworkPolicy
#################################
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-redis-policy
  labels:
    tier: airflow
    component: redis-policy
    release: {{ .Release.Name }}
    workspace: {{ .Values.workspace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      tier: airflow
      component: redis
      release: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: airflow
          release: {{ .Release.Name }}
          component: worker
    - podSelector:
        matchLabels:
          tier: airflow
          release: {{ .Release.Name }}
          component: scheduler
    - podSelector:
        matchLabels:
          tier: airflow
          release: {{ .Release.Name }}
          component: flower
    ports:
    - protocol: TCP
      port: {{ .Values.ports.redisDB }}
