#########################################
## NGINX Control Plane Metrics service ##
#########################################
{{- if or (eq .Values.global.plane.mode "control") (eq .Values.global.plane.mode "unified") }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cp-{{ template "nginx.name" . }}-metrics
  labels:
    tier: {{ template "nginx.name" . }}
    component: ingress-controller
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    plane: {{ .Values.global.plane.mode }}
spec:
  type: ClusterIP
  selector:
    tier: {{ template "nginx.name" . }}
    component: ingress-controller
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.ports.metrics }}
      targetPort: {{ .Values.ports.metrics }}
      protocol: TCP
      appProtocol: tcp
      name: nginx-metrics
      {{- if and (eq .Values.serviceType "NodePort") .Values.metricsNodePort }}
      nodePort: {{ .Values.metricsNodePort }}
      {{- end }}
{{- end }}
