##########################################
## Db migration Pre install/update Hook ##
##########################################
{{- if or (eq .Values.global.plane.mode "control") (eq .Values.global.plane.mode "unified") }}
{{- if .Values.global.flightDeck.enabled }}
apiVersion: {{ include "apiVersion.batch" . }}
kind: Job
metadata:
  name: {{ .Release.Name }}-flightdeck-db-migrations
  labels:
    tier: astronomer
    component: flightdeck-db-migrations
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    plane: {{ .Values.global.plane.mode }}
  annotations:
    "helm.sh/hook": pre-upgrade,post-install
    "helm.sh/hook-weight": "1"  # should be higher than houston's db-migration job so we can rely on its wait-for-db
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        tier: astronomer
        component: flightdeck-db-migrations
        release: {{ .Release.Name }}
        app: flightdeck-db-migrations
        version: {{ .Chart.Version }}
        plane: {{ .Values.global.plane.mode }}
        {{- include "global.podLabels" . | nindent 8 }}
      {{- if or .Values.global.podAnnotations .Values.global.istio.enabled }}
      annotations:
        {{- if .Values.global.istio.enabled }}
          sidecar.istio.io/inject: "false"
        {{- end }}
        {{- if .Values.global.podAnnotations }}
        {{- toYaml .Values.global.podAnnotations | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      nodeSelector: {{- toYaml (default .Values.global.platformNodePool.nodeSelector .Values.nodeSelector) | nindent 8 }}
      affinity: {{- toYaml (default .Values.global.platformNodePool.affinity .Values.affinity) | nindent 8 }}
      tolerations: {{- toYaml (default .Values.global.platformNodePool.tolerations .Values.tolerations) | nindent 8 }}
      restartPolicy: Never
      serviceAccountName: {{ template "flightdeck.bootstrapperServiceAccountName" . }}  # Do we need this? Should we reuse houston's or is that too dirty?
      {{- include "astronomer.imagePullSecrets" . | nindent 6 }}
      {{- if and (not .Values.houston.airflowBackendSecretName) (not .Values.houston.airflowBackendConnection) (not .Values.houston.backendSecretName) (not .Values.houston.backendConnection) }}
      # Only run etc-ssl-certs-copier and flightdeck-bootstrapper if the application is creating and managing the logical DB
      initContainers:
        - name: etc-ssl-certs-copier
          image: {{ template "commander.image" . }}
          imagePullPolicy: {{ .Values.images.commander.pullPolicy }}
          command:
            - sh
            - -c
            - |
              if [ -d /etc/ssl/certs ]; then
                cp -r /etc/ssl/certs/* /etc/ssl/certs_copy/
              else
                echo "No /etc/ssl/certs directory found, skipping copy."
              fi
          volumeMounts:
            - name: etc-ssl-certs
              mountPath: /etc/ssl/certs_copy
          securityContext:
            {{- $required := dict "readOnlyRootFilesystem" true }}
            {{- merge $required .Values.securityContext | toYaml | nindent 12 }}
          resources: {{- toYaml .Values.commander.resources | nindent 12 }}

        - name: flightdeck-bootstrapper
          image: {{ template "dbBootstrapper.image" . }}
          imagePullPolicy: {{ .Values.images.dbBootstrapper.pullPolicy }}
          securityContext:
            {{- $required := dict "readOnlyRootFilesystem" true }}
            {{- merge $required .Values.securityContext | toYaml | nindent 12 }}
          resources: {{- toYaml .Values.commander.resources | nindent 12 }}
          env:
            - name: BOOTSTRAP_DB
              valueFrom:
                secretKeyRef:
                  name: astronomer-bootstrap
                  key: connection
            {{ if .Values.global.ssl.enabled }}
            - name: SSLMODE
              value: {{ .Values.global.ssl.mode }}
            {{- end }}
            - name: DB_NAME
              value: {{ .Release.Name }}-flightdeck
            - name: SECRET_NAME
              value: {{ .Release.Name }}-flightdeck-backend
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: IN_CLUSTER
              value: "true"
          volumeMounts:
            - name: etc-ssl-certs
              mountPath: /etc/ssl/certs
            - name: tmp
              mountPath: /tmp
      {{- end }}

      containers:

        - name: flightdeck-db-migrations-job
          image: {{ template "commander.image" . }}
          imagePullPolicy: {{ .Values.images.commander.pullPolicy }}
          args:
           - "migrate"
           - "up"
           - "--db"
           - "$COMMANDER_FLIGHTDECK_DSN"
          securityContext:
            {{- $required := dict "readOnlyRootFilesystem" true }}
            {{- merge $required .Values.securityContext | toYaml | nindent 12 }}
          resources: {{- toYaml .Values.commander.resources | nindent 12 }}
          env:
            - name: COMMANDER_FLIGHTDECK_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-flightdeck-backend
                  key: connection
          {{- if .Values.flightDeck.migrations.readinessProbe }}
          readinessProbe: {{ tpl (toYaml .Values.flightDeck.migrations.readinessProbe) . | nindent 12 }}
          {{- end }}
          {{- if .Values.flightDeck.migrations.livenessProbe }}
          livenessProbe: {{ tpl (toYaml .Values.flightDeck.migrations.livenessProbe) . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: etc-ssl-certs
              mountPath: /etc/ssl/certs
            - name: tmp
              mountPath: /tmp
          {{- include "custom_ca_volume_mounts" . | indent 12 }}

      volumes:
        - name: etc-ssl-certs
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        {{- include "custom_ca_volumes" . | indent 8 }}
{{- end }}
{{- end }}
