restartPolicy: Always

kind: Deployment

podDisruptionBudget: {}
  # maxUnavailable: 0

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate

image:
  repository: quay.io/astronomer/ap-blackbox-exporter
  tag: 0.19.0-2
  pullPolicy: IfNotPresent

  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistrKeySecretName

## User to run blackbox-exporter container as
runAsUser: 1000
readOnlyRootFilesystem: true
runAsNonRoot: true

# These are set in the global values.
# nodeSelector: {}
# tolerations: {}
# affinity: {}

secretConfig: false
config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2"]
        no_follow_redirects: false
        preferred_ip_protocol: "ip4"
    tcp_connect:
      prober: tcp
      timeout: 5s
    dns_int:
      prober: dns
      dns:
        preferred_ip_protocol: "ip4"  # can be ip4 or ip6
        query_name: gcr.io # host you wish to look up as a DNS test
        transport_protocol: udp # can be udp or tcp


extraConfigmapMounts: []
  # - name: certs-configmap
  #   mountPath: /etc/secrets/ssl/
  #   subPath: certificates.crt # (optional)
  #   configMap: certs-configmap
  #   readOnly: true
  #   defaultMode: 420

## Additional secret mounts
# Defines additional mounts with secrets. Secrets must be manually created in the namespace.
extraSecretMounts: []
  # - name: secret-files
  #   mountPath: /etc/secrets
  #   secretName: blackbox-secret-files
  #   readOnly: true
  #   defaultMode: 420

allowIcmp: false

# These are overridden by what is  in the global values file
resources:
  requests:
    cpu: "60m"
    memory: "75Mi"
  limits:
    cpu: "100m"
    memory: "100Mi"

priorityClassName: ""

service:
  annotations: {}
  type: ClusterIP
  port: 9115

podAnnotations: {}

extraArgs: []
#  --history.limit=1000

replicas: 2

# these can all be overridden via the umbrella chart values file
astroServices:
  commander:
    enabled: true
  houston:
    enabled: true
  registry:
    enabled: true
  grafana:
    enabled: true
  elasticsearch:
    enabled: true
  kibana:
    enabled: true
  cliInstall:
    enabled: true
